### ISSUE TITLE
Last version broke something

### ISSUE THREAD

**Issue by myrahz** [xanthics/PoE_Weighted_Search#17]
![image](https://user-images.githubusercontent.com/13249929/59163436-22fce680-8af9-11e9-98e6-fd93504c914f.png)

Apparently Increased Damage with One Handed Melee Weapons is being used but there is no such thing on PathofExile Trade

The link provided for this search is https://xanthics.github.io/PoE_Weighted_Search/?pdot=100.2&pdotailment=100.2&pbleed=100.2&ppoison=0.0&pignite=0.0&pcolddotmulti=0.0&pchaosdotmulti=0.0&flataccuracy=15562.6&paccuracy=10343.8&pphysical=5779.8&plightning=0.0&pcold=0.0&pfire=0.0&pelemental=0.0&pchaos=0.0&pgeneric=5779.8&critchance=4824.3&critmulti=5417.8&basecrit=18844.7&attackspeed=12196.3&castspeed=0.0&penall=0.0&penlightning=0.0&pencold=0.0&penfire=0.0&flatphys=5344.9&flatlightning=0.0&flatcold=0.0&flatfire=0.0&flatchaos=0.0&chancedoubledamage=2821.4&extralightning=0.0&extracold=0.0&extrafire=0.0&extrachaos=0.0&eleaschaos=0.0&physicalasextrachaos=0.0&lightningasextrachaos=0.0&coldasextrachaos=0.0&fireasextrachaos=0.0&1powercharge=0.0&1frenzycharge=16339.1&1endurancecharge=2409.3&20dex=10343.8&20int=0.0&20str=1895.5&damageperdex=8196.7&damageperint=3857.8&damageperstr=8677.0&pdex=5156.2&pint=0.0&pstr=944.4&plowest=12534.8&plife=0.0&flatlife=0.0&pes=0.0&flates=0.0&pminion=0.0&minionattackspeed=0.0&minioncastspeed=0.0&minionflatphys=0.0&minionflatlightning=0.0&minionflatcold=0.0&minionflatfire=0.0&minionflatchaos=0.0&FrenzyCount=3&PowerCount=0&EnduranceCount=5&Flags=Melee,conditionHitRecently,DualWielding,multiplierRage,Movement,useFrenzyCharges,Channelled,Duration,Sword,Physical,useEnduranceCharges,infusedChannellingInfusion,conditionEnemyMaimed,Area,bloodSandStance,conditionEnemyIntimidated,conditionCritRecently,OneHandedWeapon,Attack,&Skill=Cyclone%20%2F%20No%20Stages&Character=37%20CURRENT%20ZERK

**Comment by xanthics** [comment]
fixed with 28718ecc3e325e205e59c542d7168d7f5e95ea1c
