### ISSUE TITLE
Comparing different quantities?

### ISSUE THREAD

**Issue by Nightblade** [xanthics/PoE_Weighted_Search#18]
(Apologies if this is hard to follow, I'm not well and I'm fighting a heap of brain-fog atm.)

Is this code is comparing different quantities of some stats?   For example, here's 3 lines from `mods.json` :  
```
"12% increased Cold Damage"
"Adds 14 to 31 Cold Damage"
"Damage Penetrates 8% Cold Resistance"
```
This is going to calculate incorrect weightings unless I'm missing something, which is quite possible.

This could be easily fixed by changing `mods.json` so that each mod is normalized to 1 unit.  Using the example above:
```
"1% increased Cold Damage"
"Adds 1 to 1 Cold Damage"
"Damage Penetrates 1% Cold Resistance"
```

**Comment by Nightblade** [comment]
Upon further investigation, I think the web page does something to normalize the stats.  If this is the case please close this issue!  :)

**Comment by coldino** [comment]
Covered in https://github.com/VolatilePulse/PoB-Item-Tester/issues/10.

**Comment by xanthics** [comment]
From mods.json `{"name": "pdot", "desc": "12% increased Damage over Time", "count": 12},`

From index.html
`for elt in doc.get(selector='input[type="number"]'):
     dps[elt.name] = float(elt.value)/float(elt.getAttribute("data-normal"))`

data-normal == count
