### ISSUE TITLE
Possible ways of bypassing the 3.9.0 restriction?

### ISSUE THREAD

**Issue by Liburia** [xanthics/PoE_Weighted_Search#20]
Having a threshold for the least impact on the DPS to count for the search sounds reasonable.

A lot of the mods are simply too weak to matter for certain builds.

**Comment by devinvisible** [comment]
Please enlighten me on the restriction?

**Comment by Liburia** [comment]
I couldn't find it myself, but the latest commit claims it.

https://github.com/xanthics/PoE_Weighted_Search/commit/2f5f8e7d6875cd155c9b339bd1ef95a3c5c3d3f8#diff-eacf331f0ffc35d4b482f1d15a887d3b

**Comment by xanthics** [comment]
discord conversation with Novynn.  There is an unknown restriction coming for "overly complex" queries.  I'm waiting for the restrictions to go live so I can test them.

First on the list is breaking mods out in to base types, so that you have to select your base item on my site before generating a query.  After that will be a secondary page where you can select some max number of mods, depending on how reasonable the restriction is, with a default behavior of deselecting the least important mods.

**Comment by devinvisible** [comment]
"I feel personally attacked" XD

**Comment by xanthics** [comment]
https://discordapp.com/channels/174993814845521922/175290321695932416/655619306872242176

+1 complexity per filter (includes And and Not blocks)
+10 complexity per Count / If block
+30 complexity per Weighted Sum block

with a max of 200

**Comment by xanthics** [comment]
```json
{
  "query": {
    "filters_(1_point)": {
      "type_filters_(1_point)": {
        "filters": {
          "category_(1_point)": {
            "option": "jewel"
          }
        }
      }
    },
    "status_(1_point)": {
      "option": "online"
    },
    "stats_(1_point)": [
      {
        "type_(30_point)": "weight",
        "value": {
          "min": 0
        },
        "filters": [
          {
            "id_(1_point)": "explicit.stat_690707482",
            "value": {
              "weight": 0.92
            }
          },
          {
            "id_(1_point)": "explicit.stat_1244360317",
            "value": {
              "weight": 0.92
            }
          },
          {
            "id_(1_point)": "explicit.stat_967627487",
            "value": {
              "weight": 0.92
            }
          }
        ]
      },
      {
        "type_(1_point)": "not",
        "filters": [
          {
            "id_(1_point)": "explicit.stat_4181057577"
          },
          {
            "id_(1_point)": "explicit.stat_2135899247"
          },
          {
            "id_(1_point)": "explicit.stat_1964333391"
          }
        ]
      }
    ]
  }
}
```
This is 42 points.  I am still going to modify for kinder searches, but I don't think my site was capable of generating a legit search that would break the rules
