### ISSUE TITLE
Search generated, site parses it but does not return results

### ISSUE THREAD

**Issue by jnitis** [xanthics/PoE_Weighted_Search#21]
Hi, I absolutely love this tool and use it each league to search for jewels.  Unfortunately this league it hasn't worked for me yet.  I update the PoB, select it, run a DPS search, click on the Search hyperlink, and it brings me to pathofexile.com/trade and pauses for longer than normal.  Eventually the animated GGG logo pops up and then the search times out without any error message.  If I click the dropdown to show all the parameters everything is there and if I deselect the weighted search portion the search works fine.

I know someone said last league the website might throw out extensive searches for performance (bots?  DDOS?) reasons but it ended up working fine all league.  Could that be what's happening here?  Seems if that were the case it'd throw an obvious error, though.

I'm happy to contact Novynn on the official forums but thought I'd start here first since you may have a relationship with him/her.

Cheers and thanks for an amazing tool!

Example search in question:

`{"query":{"filters":{"type_filters":{"filters":{"category":{"option":"jewel"}}}},"status":{"option":"online"},"stats":[{"type":"and","filters":[]}, {"type":"and","filters":[]}, {"type":"and","filters":[]}, {"type":"weight","value":{"min":847},"filters":[{"id":"explicit.stat_67169579","value":{"weight":3134.2}},{"id":"explicit.stat_146924886","value":{"weight":3085.9}},{"id":"explicit.stat_35476451","value":{"weight":1485.0}},{"id":"implicit.stat_2062174346","value":{"weight":1171.6}},{"id":"explicit.stat_2062174346","value":{"weight":1171.6}},{"id":"implicit.stat_3801128794","value":{"weight":583.3}},{"id":"explicit.stat_3801128794","value":{"weight":583.3}},{"id":"implicit.stat_3948776386","value":{"weight":479.9}},{"id":"explicit.stat_3948776386","value":{"weight":479.9}},{"id":"explicit.stat_3988349707","value":{"weight":206.5}},{"id":"implicit.stat_4055307827","value":{"weight":206.5}},{"id":"fractured.stat_4055307827","value":{"weight":206.5}},{"id":"explicit.stat_4055307827","value":{"weight":206.5}},{"id":"crafted.stat_4055307827","value":{"weight":206.5}},{"id":"implicit.stat_902747843","value":{"weight":158.98}},{"id":"explicit.stat_902747843","value":{"weight":158.98}},{"id":"crafted.stat_902747843","value":{"weight":158.98}},{"id":"explicit.stat_3916799917","value":{"weight":88.28}},{"id":"explicit.stat_2063695047","value":{"weight":88.11}},{"id":"crafted.stat_2063695047","value":{"weight":88.11}},{"id":"crafted.stat_3032590688","value":{"weight":62.0}},{"id":"explicit.stat_960081730","value":{"weight":62.0}},{"id":"implicit.stat_1760576992","value":{"weight":62.0}},{"id":"fractured.stat_1760576992","value":{"weight":62.0}},{"id":"explicit.stat_1760576992","value":{"weight":62.0}},{"id":"implicit.stat_3032590688","value":{"weight":62.0}},{"id":"fractured.stat_3032590688","value":{"weight":62.0}},{"id":"explicit.stat_3032590688","value":{"weight":62.0}},{"id":"implicit.stat_2947215268","value":{"weight":52.99}},{"id":"explicit.stat_2947215268","value":{"weight":52.99}},{"id":"crafted.stat_2947215268","value":{"weight":52.99}},{"id":"explicit.stat_2805714016","value":{"weight":52.99}},{"id":"fractured.stat_1072119541","value":{"weight":52.99}},{"id":"explicit.stat_1072119541","value":{"weight":52.99}},{"id":"implicit.stat_1839076647","value":{"weight":52.99}},{"id":"fractured.stat_1839076647","value":{"weight":52.99}},{"id":"explicit.stat_1839076647","value":{"weight":52.99}},{"id":"crafted.stat_1839076647","value":{"weight":52.99}},{"id":"implicit.stat_2154246560","value":{"weight":52.99}},{"id":"fractured.stat_2154246560","value":{"weight":52.99}},{"id":"explicit.stat_2154246560","value":{"weight":52.99}},{"id":"crafted.stat_2154246560","value":{"weight":52.99}},{"id":"implicit.stat_736967255","value":{"weight":50.47}},{"id":"fractured.stat_736967255","value":{"weight":50.47}},{"id":"explicit.stat_736967255","value":{"weight":50.47}},{"id":"crafted.stat_736967255","value":{"weight":50.47}},{"id":"implicit.stat_3319896421","value":{"weight":50.42}},{"id":"fractured.stat_3319896421","value":{"weight":50.42}},{"id":"explicit.stat_3319896421","value":{"weight":50.42}},{"id":"crafted.stat_3319896421","value":{"weight":50.42}},{"id":"explicit.stat_3519268108","value":{"weight":46.8}},{"id":"implicit.stat_3531280422","value":{"weight":46.8}},{"id":"explicit.stat_3531280422","value":{"weight":46.8}},{"id":"implicit.stat_674553446","value":{"weight":46.8}},{"id":"fractured.stat_674553446","value":{"weight":46.8}},{"id":"explicit.stat_674553446","value":{"weight":46.8}},{"id":"crafted.stat_674553446","value":{"weight":46.8}},{"id":"explicit.stat_493812998","value":{"weight":45.5}},{"id":"fractured.stat_4193088553","value":{"weight":44.77}},{"id":"explicit.stat_4193088553","value":{"weight":44.77}},{"id":"implicit.stat_967627487","value":{"weight":44.77}},{"id":"fractured.stat_967627487","value":{"weight":44.77}},{"id":"explicit.stat_967627487","value":{"weight":44.77}},{"id":"crafted.stat_967627487","value":{"weight":44.77}},{"id":"implicit.stat_1172810729","value":{"weight":39.6}},{"id":"explicit.stat_1172810729","value":{"weight":39.6}},{"id":"crafted.stat_1172810729","value":{"weight":39.6}},{"id":"explicit.stat_3495544060","value":{"weight":37.71}},{"id":"implicit.stat_2572042788","value":{"weight":36.1}},{"id":"explicit.stat_2572042788","value":{"weight":36.1}},{"id":"implicit.stat_2915373966","value":{"weight":29.43}},{"id":"fractured.stat_2915373966","value":{"weight":29.43}},{"id":"explicit.stat_2915373966","value":{"weight":29.43}},{"id":"crafted.stat_2915373966","value":{"weight":29.43}},{"id":"explicit.stat_1483753325","value":{"weight":23.85}},{"id":"implicit.stat_2672805335","value":{"weight":23.85}},{"id":"fractured.stat_2672805335","value":{"weight":23.85}},{"id":"explicit.stat_2672805335","value":{"weight":23.85}},{"id":"crafted.stat_2672805335","value":{"weight":23.85}},{"id":"crafted.stat_314741699","value":{"weight":23.85}},{"id":"implicit.stat_3759735052","value":{"weight":23.85}},{"id":"fractured.stat_3759735052","value":{"weight":23.85}},{"id":"explicit.stat_3759735052","value":{"weight":23.85}},{"id":"implicit.stat_681332047","value":{"weight":23.85}},{"id":"fractured.stat_681332047","value":{"weight":23.85}},{"id":"explicit.stat_681332047","value":{"weight":23.85}},{"id":"crafted.stat_681332047","value":{"weight":23.85}},{"id":"implicit.stat_1365052901","value":{"weight":23.85}},{"id":"explicit.stat_1365052901","value":{"weight":23.85}},{"id":"explicit.stat_3700381193","value":{"weight":20.28}},{"id":"implicit.stat_3648858570","value":{"weight":14.75}},{"id":"explicit.stat_3648858570","value":{"weight":14.75}},{"id":"implicit.stat_369494213","value":{"weight":9.77}},{"id":"explicit.stat_369494213","value":{"weight":9.77}},{"id":"implicit.stat_3964634628","value":{"weight":9.3}},{"id":"explicit.stat_3964634628","value":{"weight":9.3}},{"id":"implicit.stat_321077055","value":{"weight":9.3}},{"id":"explicit.stat_321077055","value":{"weight":9.3}},{"id":"crafted.stat_321077055","value":{"weight":9.3}},{"id":"implicit.stat_3120164895","value":{"weight":9.3}},{"id":"fractured.stat_3120164895","value":{"weight":9.3}},{"id":"explicit.stat_3120164895","value":{"weight":9.3}},{"id":"implicit.stat_1573130764","value":{"weight":9.3}},{"id":"fractured.stat_1573130764","value":{"weight":9.3}},{"id":"explicit.stat_1573130764","value":{"weight":9.3}},{"id":"crafted.stat_1573130764","value":{"weight":9.3}},{"id":"implicit.stat_2402136583","value":{"weight":8.27}},{"id":"fractured.stat_2402136583","value":{"weight":8.27}},{"id":"explicit.stat_2402136583","value":{"weight":8.27}},{"id":"crafted.stat_2402136583","value":{"weight":8.27}},{"id":"implicit.stat_1310194496","value":{"weight":8.25}},{"id":"fractured.stat_1310194496","value":{"weight":8.25}},{"id":"explicit.stat_1310194496","value":{"weight":8.25}},{"id":"crafted.stat_1310194496","value":{"weight":8.25}},{"id":"fractured.stat_1836374041","value":{"weight":8.23}},{"id":"explicit.stat_1836374041","value":{"weight":8.23}},{"id":"fractured.stat_4188894176","value":{"weight":8.23}},{"id":"explicit.stat_4188894176","value":{"weight":8.23}},{"id":"implicit.stat_2843214518","value":{"weight":8.23}},{"id":"fractured.stat_2843214518","value":{"weight":8.23}},{"id":"explicit.stat_2843214518","value":{"weight":8.23}},{"id":"implicit.stat_4251717817","value":{"weight":8.23}},{"id":"fractured.stat_4251717817","value":{"weight":8.23}},{"id":"explicit.stat_4251717817","value":{"weight":8.23}},{"id":"crafted.stat_4251717817","value":{"weight":8.23}},{"id":"explicit.stat_3392890360","value":{"weight":8.16}},{"id":"implicit.stat_2101383955","value":{"weight":8.16}},{"id":"explicit.stat_2101383955","value":{"weight":8.16}},{"id":"fractured.stat_455556407","value":{"weight":8.16}},{"id":"explicit.stat_455556407","value":{"weight":8.16}},{"id":"implicit.stat_3753703249","value":{"weight":7.42}},{"id":"explicit.stat_3753703249","value":{"weight":7.42}},{"id":"implicit.stat_4139681126","value":{"weight":6.76}},{"id":"explicit.stat_4139681126","value":{"weight":6.76}},{"id":"implicit.stat_3143208761","value":{"weight":6.76}},{"id":"explicit.stat_3143208761","value":{"weight":6.76}},{"id":"crafted.stat_3143208761","value":{"weight":6.76}},{"id":"fractured.stat_2806435316","value":{"weight":6.76}},{"id":"explicit.stat_2806435316","value":{"weight":6.76}},{"id":"implicit.stat_624954515","value":{"weight":6.76}},{"id":"fractured.stat_624954515","value":{"weight":6.76}},{"id":"explicit.stat_624954515","value":{"weight":6.76}},{"id":"explicit.stat_1477032229","value":{"weight":6.35}},{"id":"implicit.stat_3417711605","value":{"weight":6.35}},{"id":"explicit.stat_3417711605","value":{"weight":6.35}},{"id":"implicit.stat_219391121","value":{"weight":6.25}},{"id":"explicit.stat_219391121","value":{"weight":6.25}},{"id":"implicit.stat_979246511","value":{"weight":6.25}},{"id":"explicit.stat_979246511","value":{"weight":6.25}},{"id":"explicit.stat_2233361223","value":{"weight":4.92}},{"id":"fractured.stat_215124030","value":{"weight":4.92}},{"id":"implicit.stat_1662717006","value":{"weight":4.92}},{"id":"explicit.stat_215124030","value":{"weight":4.92}},{"id":"explicit.stat_1662717006","value":{"weight":4.92}},{"id":"implicit.stat_2387423236","value":{"weight":4.92}},{"id":"explicit.stat_2387423236","value":{"weight":4.92}},{"id":"crafted.stat_2387423236","value":{"weight":4.92}},{"id":"implicit.stat_215124030","value":{"weight":4.92}},{"id":"implicit.stat_4067062424","value":{"weight":4.92}},{"id":"fractured.stat_4067062424","value":{"weight":4.92}},{"id":"explicit.stat_4067062424","value":{"weight":4.92}},{"id":"crafted.stat_4067062424","value":{"weight":4.92}},{"id":"implicit.stat_2885144362","value":{"weight":4.89}},{"id":"explicit.stat_2885144362","value":{"weight":4.89}},{"id":"implicit.stat_1334060246","value":{"weight":4.89}},{"id":"explicit.stat_1334060246","value":{"weight":4.89}},{"id":"crafted.stat_1334060246","value":{"weight":4.89}},{"id":"implicit.stat_1040269876","value":{"weight":4.89}},{"id":"fractured.stat_1040269876","value":{"weight":4.89}},{"id":"explicit.stat_1040269876","value":{"weight":4.89}},{"id":"implicit.stat_1754445556","value":{"weight":4.89}},{"id":"fractured.stat_1754445556","value":{"weight":4.89}},{"id":"explicit.stat_1754445556","value":{"weight":4.89}},{"id":"crafted.stat_1754445556","value":{"weight":4.89}},{"id":"explicit.stat_4292531291","value":{"weight":4.89}},{"id":"explicit.stat_90012347","value":{"weight":4.89}},{"id":"explicit.stat_707887043","value":{"weight":4.28}},{"id":"implicit.stat_1379411836","value":{"weight":3.38}},{"id":"fractured.stat_1379411836","value":{"weight":3.38}},{"id":"explicit.stat_1379411836","value":{"weight":3.38}},{"id":"crafted.stat_1379411836","value":{"weight":3.38}},{"id":"implicit.stat_2300185227","value":{"weight":3.38}},{"id":"fractured.stat_2300185227","value":{"weight":3.38}},{"id":"explicit.stat_2300185227","value":{"weight":3.38}},{"id":"crafted.stat_2300185227","value":{"weight":3.38}},{"id":"implicit.stat_538848803","value":{"weight":3.38}},{"id":"fractured.stat_538848803","value":{"weight":3.38}},{"id":"explicit.stat_538848803","value":{"weight":3.38}},{"id":"crafted.stat_538848803","value":{"weight":3.38}},{"id":"implicit.stat_3261801346","value":{"weight":3.38}},{"id":"fractured.stat_3261801346","value":{"weight":3.38}},{"id":"explicit.stat_3261801346","value":{"weight":3.38}},{"id":"crafted.stat_3261801346","value":{"weight":3.38}},{"id":"implicit.stat_1290399200","value":{"weight":2.6}},{"id":"fractured.stat_1290399200","value":{"weight":2.6}},{"id":"explicit.stat_1290399200","value":{"weight":2.6}},{"id":"implicit.stat_690707482","value":{"weight":2.6}},{"id":"explicit.stat_690707482","value":{"weight":2.6}},{"id":"implicit.stat_240289863","value":{"weight":2.11}},{"id":"crafted.stat_3992439283","value":{"weight":2.11}},{"id":"fractured.stat_2937483991","value":{"weight":2.11}},{"id":"explicit.stat_2937483991","value":{"weight":2.11}},{"id":"implicit.stat_3556824919","value":{"weight":2.11}},{"id":"fractured.stat_3556824919","value":{"weight":2.11}},{"id":"explicit.stat_3556824919","value":{"weight":2.11}},{"id":"crafted.stat_3556824919","value":{"weight":2.11}},{"id":"implicit.stat_803737631","value":{"weight":2.03}},{"id":"fractured.stat_803737631","value":{"weight":2.03}},{"id":"explicit.stat_803737631","value":{"weight":2.03}},{"id":"crafted.stat_803737631","value":{"weight":2.03}},{"id":"implicit.stat_818778753","value":{"weight":1.81}},{"id":"explicit.stat_818778753","value":{"weight":1.81}},{"id":"explicit.stat_4164990693","value":{"weight":1.81}},{"id":"explicit.stat_276103140","value":{"weight":1.43}},{"id":"implicit.stat_587431675","value":{"weight":1.43}},{"id":"fractured.stat_587431675","value":{"weight":1.43}},{"id":"explicit.stat_587431675","value":{"weight":1.43}},{"id":"crafted.stat_587431675","value":{"weight":1.43}},{"id":"fractured.stat_2856328513","value":{"weight":1.43}},{"id":"explicit.stat_2856328513","value":{"weight":1.43}},{"id":"implicit.stat_2375316951","value":{"weight":1.43}},{"id":"fractured.stat_2375316951","value":{"weight":1.43}},{"id":"explicit.stat_2375316951","value":{"weight":1.43}},{"id":"crafted.stat_2375316951","value":{"weight":1.43}},{"id":"implicit.stat_2898434123","value":{"weight":1.43}},{"id":"explicit.stat_782323220","value":{"weight":1.18}},{"id":"implicit.stat_387439868","value":{"weight":1.18}},{"id":"fractured.stat_387439868","value":{"weight":1.18}},{"id":"explicit.stat_387439868","value":{"weight":1.18}},{"id":"crafted.stat_387439868","value":{"weight":1.18}},{"id":"implicit.stat_3141070085","value":{"weight":1.18}},{"id":"fractured.stat_3141070085","value":{"weight":1.18}},{"id":"explicit.stat_3141070085","value":{"weight":1.18}},{"id":"implicit.stat_3291658075","value":{"weight":0.91}},{"id":"fractured.stat_3291658075","value":{"weight":0.91}},{"id":"explicit.stat_3291658075","value":{"weight":0.91}},{"id":"crafted.stat_3291658075","value":{"weight":0.91}},{"id":"implicit.stat_2231156303","value":{"weight":0.28}},{"id":"fractured.stat_2231156303","value":{"weight":0.28}},{"id":"explicit.stat_2231156303","value":{"weight":0.28}},{"id":"crafted.stat_2231156303","value":{"weight":0.28}}]},{"type":"not","filters":[{"id":"explicit.stat_4181057577"},{"id":"explicit.stat_2135899247"},{"id":"explicit.stat_1964333391"}]}]}}`

**Comment by coldino** [comment]
Yup I've come across this as well. No refusal or error, just no results. Perhaps they have some form of dynamic scaling during busy time and DDoS. The trade website has been pretty slow recently.

More importantly, I've noticed that the number of results, rather than the complexity of the query, affects whether results are shown. As an example I was searching for a one-handed weapon and despite trimming many of the low value query lines I could not get any results. Simply changing the category to wands returned results every time.

**Comment by xanthics** [comment]
I've @ ed Novynn in discord.  Will update when I know more.

**Comment by xanthics** [comment]
![image](https://user-images.githubusercontent.com/3137623/76911766-e40d7580-686e-11ea-9318-e1c5924928a1.png)

**Comment by xanthics** [comment]
Mitigated as much as possible due to new weighted search restrictions 7786556f0f6f5ff69d18495ab1c4738ac7e60992
