### ISSUE TITLE
General Cry Negative Results

### ISSUE THREAD

**Issue by livejamie** [xanthics/PoE_Weighted_Search#37]
Trying to search for General Cry jewels and I get this search: 

https://xanthics.github.io/PoE_Weighted_Search/?vals=4,-4008679.2,-3843010.4,-4020037.2,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-3828314.0,-4098457.3,-4098457.3,-3954319.7,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-3954319.7,-4098457.3,-3954443.4,-3954443.4,-4098457.3,-4098457.3,-4008819.0,-3901281.4,-3567450.1,-3839209.2,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-3830163.8,-4002590.8,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4035275.5,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4045097.1,-4024461.2,-4098457.3,-4098457.3,-4098457.3,-4050473.7,-3966271.9,-4014006.9,-3809075.5,-4098457.3,-4098457.3,-4002008.7,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4021435.8,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098333.6,-4098457.3,-4098333.6,-4098333.6,-4098333.6,-4098457.3,-4098457.3,-4098109.9,-4098109.9,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4098457.3,-4034395.2,-4098457.3,-4098457.3,-3871662.0,-3954319.7&BlitzCount=20&FrenzyCount=3&PowerCount=3&EnduranceCount=3&Flags=Melee,buffFortify,ConsumedCorpseRecently,HitRecently,EnemyTaunted,enemyIsBoss,EnemyIntimidated,OneHandedWeapon,UsedWarcryRecently,Channelled,infusedChannellingInfusion,CreatesMirageWarrior,Physical,buffOnslaught,Area,UsesSupportedTrigger,Attack,CritRecently,UsedWarcryInPast8Seconds,Sword,Shield,&Skill=General%27s%20Cry%2C%20Blade%20Flurry%20%2F%20Blade%20Flurry&Character=General%20Cry'

This is the POB: https://pastebin.com/XWHv2uQs

If I remove General's Cry from the config it seems to fix the issue

**Comment by xanthics** [comment]
`If you are using a minion skill as primary and see all 0 weights, try using FullDPS in PoB first.`

It's a bug with path of building and minion skills.  Enabling Full DPS with 1 instance of GC gives correct results

https://xanthics.github.io/PoE_Weighted_Search/?vals=4,86674.6,249531.5,75589.1,,,,,,,263008.9,,,140191.4,,,,,,140191.4,,140103.9,140103.9,,,87504.1,192705.0,518950.6,253953.6,,,,,,262303.3,93642.1,,,,,61722.1,,,,,,,,,,47987.7,66507.1,,,,46680.9,128561.5,82156.3,281483.6,,,93842.6,,,,,,,,,,,,,,69230.0,,,,,,,,,,,,87.5,,87.5,87.5,87.5,,,317.8,317.8,,,,,,,,,,57566.5,,,218886.5,140191.4&BlitzCount=20&FrenzyCount=3&PowerCount=3&EnduranceCount=3&Flags=Melee,buffFortify,ConsumedCorpseRecently,HitRecently,EnemyTaunted,enemyIsBoss,CritRecently,Sword,UsedWarcryRecently,Channelled,infusedChannellingInfusion,CreatesMirageWarrior,Physical,buffOnslaught,EnemyIntimidated,Attack,Area,OneHandedWeapon,UsedWarcryInPast8Seconds,UsesSupportedTrigger,Shield,&Skill=Blade%20Flurry%20%2B%20Blade%20Flurry%20%2B%20Best%20Bleed%20DPS%20%2B%20Full%20Impale%20DPS&Character=gc

Without FullDPS the pob-item-tester will use combined dps by default, for most skills.  Example if you added an empty jewel socket and created a 12% phys damage jewel to put in it

![image](https://user-images.githubusercontent.com/3137623/132953267-c9537ec5-f53e-4ab7-8835-c90d252cfd2c.png)

**Comment by livejamie** [comment]
Oh thanks for the helpful response, I did see the mention of enabling full DPS but I didn't know what was meant by that until now.
