### ISSUE TITLE
[Request] Ignore Attack Speed Option

### ISSUE THREAD

**Issue by livejamie** [xanthics/PoE_Weighted_Search#39]
For CoC characters, the amount of attack speed you hit for certain thresholds is very important and requires a lot of calculations.

The weighted search really loves attack speed by default for a lot of builds.

It would be nice to be able to check a box in this bank of options to ignore all attack speed mods, rather than having to manually do it every search.

Thanks!

![image](https://user-images.githubusercontent.com/49513/147644995-fc02756d-93b1-4a2a-b0a3-f1d80b27a19f.png)

**Comment by xanthics** [comment]
Added toggles for cast and attack speed that are saved in local storage e051921c10d27915236912681c278935c57f6179
