### ISSUE TITLE
Using Vall Summon Skeletons with Full DPS and still getting 0's on weights.

### ISSUE THREAD

**Issue by codeninja** [xanthics/PoE_Weighted_Search#43]
![image](https://user-images.githubusercontent.com/14914/169867987-78662ed3-7cef-4166-8b18-0614aeb02d71.png)

![image](https://user-images.githubusercontent.com/14914/169869777-3db65b25-0d3f-4b4b-aa2b-6cbb245a7e6a.png)

It doesn't seem to be picking up the skill.

**Comment by xanthics** [comment]
Unfortunately this is a PoB + [Item Tester](https://github.com/VolatilePulse/PoB-Item-Tester) Issue, not a website issue.  I see you found the discord so hopefully we can get to the bottom of this.
