### ISSUE TITLE
All builds showing a weight of 0

### ISSUE THREAD

**Issue by Bxmnx** [xanthics/PoE_Weighted_Search#44]
I've tried several builds and just creating random builds from scatch in POB. No matter what I'm getting a weight of zero for everything

**Comment by xanthics** [comment]
Should be working now 646e9b95364333e361241c4f8f30f238c60524ba

**Comment by Bxmnx** [comment]
This error seems to be related, 
"You are using an unsupported version of mods.json, this should automatically update when you (re)start PoB-Item-Tester
Current version is 6, you are using 7."
However, it automatically updates the mod.json

**Comment by Bxmnx** [comment]
> Should be working now [646e9b9](https://github.com/xanthics/PoE_Weighted_Search/commit/646e9b95364333e361241c4f8f30f238c60524ba)

Yep, thanks
