### ISSUE TITLE
Automating the PoB part

### ISSUE THREAD

**Issue by coldino** [xanthics/PoE_Weighted_Search#5]
I've made a script that allows PoB to calculate all of the DPS weights for GenerateSearch.py automatically. It can be run without PoB's UI showing for full automation. Unfortunately, with the need to copy/paste the output into GenerateSearch.py, the editing of the search terms, and the requirement to have Python installed, this can't really be considered usable by most people.

This would all be a lot more user friendly if you could add the facility to your webpage to allow this script to post data directly to it, to pre-fill all of the numerical fields.  Maybe in future the PoB maintainer would accept a new button that fired off this script, taking you directly to your webpage.

At the moment I'm producing output designed to be pasted into the Python:
```
                "ele as chaos": 881.7,
                "pen fire": 876.1,
                "extra random": 0.0,
                "% generic": 255.1,
                "+1 endurance charge": 1273.3,
                "+1 frenzy charge": 0.0,
                "% elemental": 255.1,
                "flat chaos": 14.5,
                "flat accuracy": 0.0,
                "% chaos": 0.0,
                "% physical": 0.0,
                "flat cold": 54.3,
                "% cold": 2.9,
                "crit chance": 0.0,
                "extra chaos": 881.7,
                "crit multi": 0.0,
                "extra cold": 0.0,
                "flat phys": 25.9,
                "pen cold": 5.7,
                "extra lightning": 0.0,
                "flat lightning": 54.2,
                "attack speed": 548.9,
                "flat fire": 150.8,
                "pen lightning": 0.0,
                "% fire": 252.2,
                "pen all": 881.7,
                "+1 power charge": 0.0,
                "% accuracy": 0.0,
                "extra fire": 0.0,
                "cast speed": 0.0,
                "% lightning": 0.0,
```
...but it could of course easily be full JSON or even URL-encoded query parameters if that is easier.

Script: <https://github.com/VolatilePulse/PoB-Item-Tester/blob/master/ItemTester/SearchDPS.lua>

**Comment by xanthics** [comment]
Interesting.  A person [here](https://www.reddit.com/r/pathofexile/comments/9lyeoc/official_trade_site_weighted_sum_search_generator/e7btj6p/) wrote some lua code that generates javascript that you can just paste in to a developer console.  

I can run anything on the website that is necessary/helpful.  So for example it can be set up to have a text box to paste output from your code to fill in the page.  That output could be plain text, or json, or whatever format makes the most sense.

If you'd like to hash out specifics, send me a message on reddit (/u/xanthics) and I'll send you my discord handle.

**Comment by coldino** [comment]
I've had a look at the the script provided by cm_pony on reddit. It's a great solution for those that like to tinker with code. Certainly nicer to use a flask to generate the options, but expecting a user to modify PoB isn't a good way forward. Here's my take on the solutions, in order of my preference:

1) Best-case: Re-implement all of your code in Lua with PoB and attach it to a simple UI that allows selecting tags/classes/etc, then launching the search in a browser. If accepted by the PoB team this would be ideal for all users.
2) Extension of my external Lua script that runs with PoB's runtime and takes you direct to your website, pre-filled. No Lua/Python runtime required by the user, but still a separate download.
3) Extension of cm_pony's script to generate the site link directly in PoB. Better than copy/paste into the dev console, but still requires editing PoB's source and the associated issue with its update system.

For any solution involving your site you'll need to handle the values as a query parameter. Would a simple format such as this work for you?
```
http://gw2crafts.net/pobsearch/modsearch.html?cast%20speed=0&...
```

...which your page could read very simply and auto-fill. It would also be a solution to "saving" data as it could be bookmarked. If you also allow tags to be specified an extension to the PoB interface might be able to provide those, later on.

**Comment by xanthics** [comment]
1.  I have no experience with writing Lua, so I wouldn't know where to begin with that.  I would welcome a rewrite though as I anticipated my website being a temporary solution for generating queries.

2&3. Query parameters are easy to implement with Brython.  If 1 doesn't gain any traction I can implement this soon.

**Comment by xanthics** [comment]
I attempted to run your code and am having issues with "dofile("Launch.lua")" as the file doesn't appear to exist.  Do I need to install something for that file?

**Comment by coldino** [comment]
Apologies... forgot about this for a few days.

The files have been re-arranged to be easier to run. I'll update within the next couple of hours with your newest mod lines. There's a `testdps.bat` file in the root that shows how it needs to be run (and you can replace the `LuaJIT.exe` we use with the full `Path of Building.exe` - only downside is the annoying console window):
```bat
cd %POBPATH%
"Path of Building.exe" %SCRIPTPATH%\SearchDPS.lua CURRENT
```

I think it would be easiest if you go ahead and add the querystring processing to your website. I'll change the script to launch the browser directly then.

**Comment by xanthics** [comment]
http://gw2crafts.net/pobsearch/modsearch.html?Cold=True&flat%20accuracy=100

All of the table values accept numbers, all of the check boxes can be set with "True"

**Comment by coldino** [comment]
Great, I'll update my script to post to your page directly.

---

Sadly, it appears you are right about installing PoB from the setup exe. When extracting from the (binary) zip, there's a `launch.lua` present. The `xml` module is in the a subdirectory and requires LUA_PATH to be set correctly. Sorry, I missed that part of the bat file out of the snippet:
```bat
set LUA_PATH=%POBPATH%\lua\?.lua;%BASEDIR%\ItemTester\?.lua
```
I'm not sure how to solve the missing `launch.lua` issue. Might be time to talk to the PoB team. It has to be built into the exe somehow, but I don't know if we can use it at all.

---

The flask issue seems likely to be true. A separate, detached jewel socket might be a better option and not require you to empty an existing socket, but I don't know how that might be possible.

**Comment by coldino** [comment]
Script updated. Adds all mod effects to the URL and launches it. For example [a Whispering Ice build's output](http://gw2crafts.net/pobsearch/modsearch.html?flat%20accuracy=0.0&%25%20accuracy=0.0&%25%20physical=0.0&%25%20lightning=0.0&%25%20cold=1101.0&%25%20fire=1101.0&%25%20elemental=1101.0&%25%20chaos=0.0&%25%20generic=1101.0&crit%20chance=0.0&crit%20multi=0.0&attack%20speed=0.0&cast%20speed=0.0&pen%20all=4431.1&pen%20lightning=0.0&pen%20cold=0.0&pen%20fire=4431.1&flat%20phys=234.9&flat%20lightning=1008.5&flat%20cold=1732.2&flat%20fire=1502.0&flat%20chaos=0.0&extra%20lightning=0.0&extra%20cold=0.0&extra%20fire=0.0&extra%20chaos=0.0&ele%20as%20chaos=0.0&%2B1%20power%20charge=0.0&%2B1%20frenzy%20charge=0.0&%2B1%20endurance%20charge=0.0&20%20dex=0.0&20%20int=0.0&20%20str=0.0&damage%20per%20dex=1646.8&damage%20per%20int=9892.4&damage%20per%20str=1741.7&%25%20dex=0.0&%25%20int=0.0&%25%20str=0.0&%25%20lowest=5037.6&).

I haven't looked at ways to generate the flags/tags from the main skill yet, but it would never be complete or perfect anyway. 

There's another problem with using flasks. With this Whispering Ice build damage scales from INT, yet INT doesn't seem to apply to a flask at all.

**Comment by coldino** [comment]
Found a way to avoid using a flask by using a pretend passive node and fixed +attr and +%attr stats. You were just missing the initial `+`. See VolatilePulse/PoB-Item-Tester@949da6ccc76efb1fc9c2c8df1ec7e4fb741dda51.

You should be able to run it from the AHK script (as long as `launch.lua` is present) by pressing Ctrl-Windows-D.  Also, Ctrl-Windows-C runs a comparison on the PoE item currently on your clipboard.

**Comment by xanthics** [comment]
Interesting on the `+`.  I took the mod description directly from the trade site api.  Just means I'll have to add a translation layer.

**Comment by coldino** [comment]
Now added flag extraction from PoB directly. As it turns out this can be quite extensive.

[A Molten Strike build](http://gw2crafts.net/pobsearch/modsearch.html?flat%20accuracy=666.0&%25%20accuracy=666.0&%25%20physical=0.0&%25%20lightning=15.9&%25%20cold=0.0&%25%20fire=1294.9&%25%20elemental=1309.1&%25%20chaos=124.6&%25%20generic=1309.1&crit%20chance=0.0&crit%20multi=0.0&attack%20speed=2419.5&cast%20speed=0.0&pen%20all=4813.6&pen%20lightning=55.2&pen%20cold=0.0&pen%20fire=4758.4&flat%20phys=258.5&flat%20lightning=746.5&flat%20cold=456.3&flat%20fire=1873.4&flat%20chaos=22.6&extra%20lightning=0.0&extra%20cold=0.0&extra%20fire=0.0&extra%20chaos=6768.7&ele%20as%20chaos=6768.7&%2B1%20power%20charge=0.0&%2B1%20frenzy%20charge=3518.1&%2B1%20endurance%20charge=547.6&20%20dex=0.0&20%20int=0.0&20%20str=0.0&damage%20per%20dex=1964.6&damage%20per%20int=982.5&damage%20per%20str=1964.6&%25%20dex=0.0&%25%20int=0.0&%25%20str=0.0&%25%20lowest=3052.8&Melee=True&Two%20Handed%20Sword=True&Projectile=True&Frenzy=True&Two%20Handed%20Weapon=True&Flasked=True&Taunted=True&Sword=True&Attack=True&Elemental=True&Ignited=True&Intimidated=True&Fire=True&Crit=True&Endurance=True&Burning=True&Area=True&Blinded=True&)
Using your current flags breakdown we get:
**Tags**: Attack
**Weapons**: Sword, Two Handed Sword
**Tags**: Melee, Area, Projectile, Fire, Elemental
**Hands**: Two Handed Weapon
**Charges**: Frenzy, Endurance
**Recently**: Crit  <- *does not work*
**You have/are**: Flasked
**Enemy is**: Taunted, Ignited, Intimidated. Burning, Blinded *(most not supported by the website yet)*

I've tested it on a few different types of build. Significant flags that are missing support on your end would be DamageOverTime and the various other enemy effects like burning. Setting Crit=True does not appear to work at all. I can open different issues for these if you would prefer.

Not tested with minion builds, yet.

**Comment by xanthics** [comment]
There are currently 4 mods that should have support for 'crit recently'.  In addition to fixing the 'too long' uri issue, I'm going to set up some tests so I can make sure all the mods are selectable.

**Comment by xanthics** [comment]
I've added instructions to the page for your script(links/etc).  I added a few mods today and will be adding some mods tomorrow(will be support for bleeding, poison, generic dot).  After tomorrow, if you would like, make a new issue with mods that my page doesn't support.

**Comment by coldino** [comment]
You could replace those instructions with just "Run the AHK script and press Ctrl-Windows-D".
Sadly it still relies on the zip-install of PoB, of course.

AHK FYIs:
* With a PoE item on your clipboard, Ctrl-Windows-C shows a pop-up with its stat effects.
* Add the Alt key to either action and it'll pop up a build picker first.

I'm working on getting charge counts included.

**Comment by xanthics** [comment]
Updated coldino script instructions to use the AHK script.

**Comment by coldino** [comment]
Charge counts, skill name and character (build) name included.

**Comment by xanthics** [comment]
Added new mods: 
- '% dot' 
- '% bleed' 
- '% poison' 
- '% ignite'

Added new flags: enemy is 
- 'Bleeding' 
- 'Poisoned' 
- 'Ignited' 
- 'Burning' 
- 'Frozen' 
- 'Shocked'

**Comment by coldino** [comment]
Added 👍

**Comment by xanthics** [comment]
Updated mods.json for life/es mods.  Going to add all the minion stuff tomorrow.  With your script I guess I don't really have to worry too much about clutter.

**Comment by coldino** [comment]
Added, but I can't test as I haven't been able to get to pathofexile.com for a couple of days now.

**Comment by coldino** [comment]
I'll try to work out a way to get mods directly from your mods file.

When the AHK script is properly released it'll only be bundled with the Lua runtime and will download the required files on first use - so could download your `mods.json` directly. Only problem is, there's no JSON reader available in PoB.

Not sure if it would be best to download your mods file directly or have a tested one checked in to the other repo.
