### ISSUE TITLE
Request URI Too Large

### ISSUE THREAD

**Issue by coldino** [xanthics/PoE_Weighted_Search#7]
Certain combinations of inputs to your website generate a  search URL that the trade site will not accept, generating a `414 Request-URI Too Large` response.

Is it possible to post the data in the body, rather than the URL?

[Example](http://gw2crafts.net/pobsearch/modsearch.html?flat%20accuracy=2514.5&%25%20accuracy=2514.5&%25%20physical=886.0&%25%20lightning=742.0&%25%20cold=626.8&%25%20fire=815.7&%25%20elemental=2184.5&%25%20chaos=0.0&%25%20generic=2184.5&crit%20chance=0.0&crit%20multi=0.0&attack%20speed=4199.6&cast%20speed=0.0&pen%20all=1587.5&pen%20lightning=0.0&pen%20cold=0.0&pen%20fire=1587.5&flat%20phys=1379.3&flat%20lightning=3969.5&flat%20cold=2478.2&flat%20fire=6263.2&flat%20chaos=68.4&extra%20lightning=3357.1&extra%20cold=3440.0&extra%20fire=7071.3&extra%20chaos=12902.7&ele%20as%20chaos=12438.0&%2B1%20power%20charge=0.0&%2B1%20frenzy%20charge=0.0&%2B1%20endurance%20charge=0.0&20%20dex=1257.3&20%20int=0.0&20%20str=274.7&damage%20per%20dex=4026.6&damage%20per%20int=3109.1&damage%20per%20str=1821.6&%25%20dex=1257.3&%25%20int=0.0&%25%20str=132.1&%25%20lowest=5855.0&Melee=True&Axe=True&Fire=True&Projectile=True&Area=True&Elemental=True&One%20Handed%20Axe=True&Attack=True&Shield=True&).

**Comment by xanthics** [comment]
I'll take a look at this over the weekend.  I'm not quite sure how to approach fixing this yet.

**Comment by xanthics** [comment]
Because of the way the api is [set up](https://www.reddit.com/r/pathofexiledev/comments/7aiil7/how_to_make_your_own_queries_against_the_official/) I would have to do a post, and then read the reply.  But the active CORS policy won't allow me to do that from the webpage.  Not sure how to circumvent the cross domain policy yet, since I need to be able to read the response.

**Comment by xanthics** [comment]
Or with firefox. 
![image](https://user-images.githubusercontent.com/3137623/48310273-3a62f980-e541-11e8-9840-95ef9c12442d.png)

**Comment by xanthics** [comment]
From support:

> We do not support CORS pre-flight requests on our official or private APIs. Usually this isn't a problem as most APIs require a GET request (as you initially found), but in your case it will prevent you from being able to use a POST to the trade endpoint when faced with extremely large queries. Supporting OPTIONS requests is something we would like to provide, but unfortunately would take a significant rewrite and won't be completed as soon as you may want. Instead I'll see if we can increase the URI limit.

**Comment by coldino** [comment]
Well, it's a more positive response that you would expect from most games companies.
Let's hope the limit is increased and this is a non-issue for a while.

**Comment by xanthics** [comment]
Agreed.  If it is still an issue I can disable less used mods or start grouping them by the slots they can appear on.

**Comment by coldino** [comment]
Simple suggestion:
Filter the output, removing any mods that have a weight of 0.
If more is required, you can cull anything that's less than a few % of the biggest weight.

**Comment by xanthics** [comment]
Mods with weight 0 are already being removed.  But perhaps mods that are less than a certain % of generic damage.

**Comment by xanthics** [comment]
And the most terrible idea I have is to create a python(or ahk) script via the webpage that you download and it then does the page opening for you.  But that is a dumb amount of steps.

**Comment by xanthics** [comment]
As a temporary solution, I have created a python script that prompts for a string that is output by the webpage.  It will then directly open the webpage,  Too many steps for a real solution, but works in the short term.
