### ISSUE TITLE
Incorrect generation with "increased damage per NN of Attribute"

### ISSUE THREAD

**Issue by coldino** [xanthics/PoE_Weighted_Search#9]
This [Whispering Ice build](http://gw2crafts.net/pobsearch/modsearch.html?%25%20dot=0.0&%25%20bleed=0.0&%25%20poison=0.0&%25%20ignite=0.0&flat%20accuracy=0.0&%25%20accuracy=0.0&%25%20physical=0.0&%25%20lightning=0.0&%25%20cold=120.1&%25%20fire=120.1&%25%20elemental=120.1&%25%20chaos=0.0&%25%20generic=120.1&crit%20chance=0.0&crit%20multi=0.0&attack%20speed=0.0&cast%20speed=0.0&pen%20all=688.4&pen%20lightning=0.0&pen%20cold=0.0&pen%20fire=688.4&flat%20phys=25.4&flat%20lightning=109.1&flat%20cold=187.1&flat%20fire=162.3&flat%20chaos=0.0&extra%20lightning=0.0&extra%20cold=0.0&extra%20fire=0.0&extra%20chaos=0.0&ele%20as%20chaos=0.0&lightning%20as%20extra%20chaos=0.0&cold%20as%20extra%20chaos=0.0&fire%20as%20extra%20chaos=0.0&%2B1%20power%20charge=0.0&%2B1%20frenzy%20charge=0.0&%2B1%20endurance%20charge=0.0&20%20dex=20.2&20%20int=196.4&20%20str=0.0&damage%20per%20dex=181.3&damage%20per%20int=1081.1&damage%20per%20str=191.2&%25%20dex=20.2&%25%20int=65.8&%25%20str=0.0&%25%20lowest=550.9&%25%20life=0.0&flat%20life=0.0&%25%20es=0.0&flat%20es=0.0&%25%20minion=0.0&minion%20attack%20speed=0.0&minion%20cast%20speed=0.0&minion%20flat%20phys=0.0&minion%20flat%20lightning=0.0&minion%20flat%20cold=0.0&minion%20flat%20fire=0.0&minion%20flat%20chaos=0.0&Hit=True&Chilled=True&Duration=True&Spell=True&Frenzy%20Count=0&Staff=True&Recent%20Hit=True&Area=True&Flasked=True&Power%20Count=0&Elemental=True&Two%20Handed%20Weapon=True&Cold=True&Endurance%20Count=0&Skill=Icestorm&Character=Zamhi) scales DPS most heavily from INT and also from the lowest attribute.

The PoB side submits different numbers for each attribute:
![image](https://user-images.githubusercontent.com/28345893/48958619-41820280-ef58-11e8-9f61-cf6d70db4fb8.png)

...but the generated filters for each attribute come out all the same:
![image](https://user-images.githubusercontent.com/28345893/48958604-1dbebc80-ef58-11e8-9cc9-65fbb0f71d88.png)

Some copy/paste issue?

**Comment by xanthics** [comment]
https://github.com/xanthics/PoE_Weighted_Search/commit/a335926d20300a639b586305e93d18b543586e03
